REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\Calcp\Calcp.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\Calcp\arm\gccmain.o" -c "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Calcp\include" -I "D:\MyGitHub\Calcp\include\service" -I "D:\MyGitHub\Calcp\include\component" -I "D:\MyGitHub\Calcp\ResID" -I "D:\MyGitHub\Calcp\src\app\widget" -I "D:\MyGitHub\Calcp\src\app\launcher" -I "D:\MyGitHub\Calcp\src\app\wallpaper" -I "D:\MyGitHub\Calcp\src\app\screen_lock" -I "D:\MyGitHub\Calcp\include\service" -I "D:\MyGitHub\Calcp\include\component" -I "D:\MyGitHub\Calcp\include\service" -I "D:\MyGitHub\Calcp\src\framework" -I "D:\MyGitHub\Calcp\src\framework\ui_core\base" -I "D:\MyGitHub\Calcp\src\framework\ui_core\mvc" -I "D:\MyGitHub\Calcp\src\framework\ui_core\pme" -I "D:\MyGitHub\Calcp\src\framework\mmi_core" -I "D:\MyGitHub\Calcp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Calcp\src\component" -I "D:\MyGitHub\Calcp\src\ui_engine\framework\xml" -I "D:\MyGitHub\Calcp"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\Calcp\arm\Calcp.o" -c "d:\MyGitHub\Calcp\Calcp.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Calcp\include" -I "D:\MyGitHub\Calcp\include\service" -I "D:\MyGitHub\Calcp\include\component" -I "D:\MyGitHub\Calcp\ResID" -I "D:\MyGitHub\Calcp\src\app\widget" -I "D:\MyGitHub\Calcp\src\app\launcher" -I "D:\MyGitHub\Calcp\src\app\wallpaper" -I "D:\MyGitHub\Calcp\src\app\screen_lock" -I "D:\MyGitHub\Calcp\include\service" -I "D:\MyGitHub\Calcp\include\component" -I "D:\MyGitHub\Calcp\include\service" -I "D:\MyGitHub\Calcp\src\framework" -I "D:\MyGitHub\Calcp\src\framework\ui_core\base" -I "D:\MyGitHub\Calcp\src\framework\ui_core\mvc" -I "D:\MyGitHub\Calcp\src\framework\ui_core\pme" -I "D:\MyGitHub\Calcp\src\framework\mmi_core" -I "D:\MyGitHub\Calcp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Calcp\src\component" -I "D:\MyGitHub\Calcp\src\ui_engine\framework\xml" -I "D:\MyGitHub\Calcp"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\Calcp\Calcp.axf"  "D:\MyGitHub\Calcp\arm\gccmain.o"  "D:\MyGitHub\Calcp\arm\Calcp.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc_t\scat.ld" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc_t\percommon.a"
REM Pack resource to app 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\Calcp\Calcp.pkd" -e AXF "D:\MyGitHub\Calcp\Calcp.vcproj" "D:\MyGitHub\Calcp\Calcp.axf"
REM Add tag infromation 
"C:\Program Files\MRE SDK V3.0.00\tools\PackDigist.exe" "D:\MyGitHub\Calcp\Calcp.vcproj" "Calcp" "0.1.0" "RDZDX" "0" "NotSupportBg" "Not Support rotate" "Calcp" "Calcp" "Calcp" "9246012102087182" "content" "" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\Calcp\arm D:\MyGitHub\Calcp\build.log

